import PDFDocument from "pdfkit";
import { IProject } from "../models/Project";
import { ILandRecord } from "../models/LandRecord";

export class PdfReportService {
  public static generateProjectReport(project: IProject, parcels: ILandRecord[]): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: "A4" });
      const buffers: Buffer[] = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", (err) => reject(err));

      // Header
      doc.fillColor("#1e3a8a").fontSize(20).text("GOVERNMENT OF INDIA - LANDGUARD AI", { align: "center" });
      doc.fontSize(14).text("PREDICTIVE LAND ACQUISITION & RISK REPORT", { align: "center" });
      doc.moveDown(1);

      // Project Overview Section
      doc.fillColor("#000000").fontSize(12).text(`Project ID: ${project.id}`, { underline: true });
      doc.text(`Project Name: ${project.name}`);
      doc.text(`State / District: ${project.state} / ${project.district}`);
      doc.text(`Project Type: ${project.type}`);
      doc.text(`Required Area: ${project.landRequired} Hectares | Acquired: ${project.landAcquired} Hectares`);
      doc.text(`Acquisition Progress: ${project.progress}%`);
      doc.text(`Overall Delay Risk: ${project.delayRisk} | Predicted Delay: ${project.predictedDelay} Days`);
      doc.text(`Cost Overrun Estimate: ${project.costOverrun} Crores`);
      doc.moveDown(1);

      // Parcels Table Breakdown
      doc.fillColor("#1e3a8a").fontSize(14).text("Land Parcels Breakdown", { underline: true });
      doc.moveDown(0.5);

      doc.fillColor("#000000").fontSize(10);
      parcels.forEach((p, idx) => {
        doc.text(
          `${idx + 1}. Survey #${p.surveyNumber || p.id} | Owner: ${p.ownerName || 'N/A'} | Area: ${p.landArea} Acres | Risk: ${p.riskLevel || 'Low'} (${p.delayProbability || 20}%)`
        );
      });

      doc.moveDown(2);
      doc.fontSize(8).fillColor("#666666").text(`Report Generated by LandGuard AI System on ${new Date().toLocaleString()}`, { align: "center" });

      doc.end();
    });
  }

  public static generateLandParcelReport(parcel: ILandRecord): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: "A4" });
      const buffers: Buffer[] = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", (err) => reject(err));

      // Header
      doc.fillColor("#1e3a8a").fontSize(20).text("LANDGUARD AI - INDIVIDUAL PARCEL RISK DOSSIER", { align: "center" });
      doc.moveDown(1);

      doc.fillColor("#000000").fontSize(12);
      doc.text(`Parcel ID: ${parcel.id}`);
      doc.text(`Survey Number: ${parcel.surveyNumber || 'N/A'}`);
      doc.text(`Landowner Name: ${parcel.ownerName || 'N/A'}`);
      doc.text(`District / State: ${parcel.district}, ${parcel.state || 'Tamil Nadu'}`);
      doc.text(`Land Area: ${parcel.landArea} Acres (${parcel.landType})`);
      doc.text(`Acquisition Stage: ${parcel.acquisitionStage}`);
      doc.text(`Compensation Status: ${parcel.compensationStatus} (INR ₹${(parcel.compensationAmount || 0).toLocaleString()})`);
      doc.moveDown(1);

      doc.fillColor("#b91c1c").fontSize(14).text("AI Predictive Risk Metrics");
      doc.fillColor("#000000").fontSize(10);
      doc.text(`Delay Probability: ${parcel.delayProbability || 20}%`);
      doc.text(`Risk Level Classification: ${parcel.riskLevel || 'Low'}`);
      doc.text(`Predicted Additional Delay: ${parcel.predictedDelayDays || 30} Days`);
      doc.text(`Legal Risk Probability: ${parcel.legalRiskProbability || 10}% (${parcel.legalRiskLevel || 'Low'})`);
      doc.text(`Expected Additional Cost Overrun: ₹${(parcel.expectedAdditionalCost || 0).toLocaleString()}`);
      doc.moveDown(1);

      if (parcel.recommendedAction) {
        doc.fillColor("#1e3a8a").fontSize(12).text("Recommended Action:");
        doc.fillColor("#000000").fontSize(10).text(parcel.recommendedAction);
      }

      doc.moveDown(2);
      doc.fontSize(8).fillColor("#666666").text(`Official Government Record Dossier - Generated on ${new Date().toLocaleString()}`, { align: "center" });

      doc.end();
    });
  }

  public static generateAuditPdf(reportData: {
    title: string;
    date?: string;
    meta?: Record<string, any>;
    metrics?: Array<{ label: string; value: string }>;
    bodyText?: string;
  }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: "A4" });
      const buffers: Buffer[] = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", (err) => reject(err));

      // Government Header
      doc.fillColor("#1e3a8a").fontSize(18).text("REVENUE DEPARTMENT - GOVERNMENT OF TAMIL NADU", { align: "center" });
      doc.fontSize(12).fillColor("#475569").text("SPECIAL LAND ACQUISITION (SLA) OFFICIAL AUDIT DOSSIER", { align: "center" });
      doc.moveDown(1);

      // Title & Date
      doc.fillColor("#0f172a").fontSize(14).text(reportData.title.toUpperCase(), { underline: true });
      doc.fontSize(10).fillColor("#64748b").text(`Date of Generation: ${reportData.date || new Date().toLocaleDateString()}`);
      doc.text(`Digital Seal: SHA256-AUTHENTICATED-${Date.now().toString(16).toUpperCase()}`);
      doc.moveDown(1);

      // Metadata Box
      if (reportData.meta && Object.keys(reportData.meta).length > 0) {
        doc.fillColor("#1e3a8a").fontSize(12).text("Metadata Overview", { underline: true });
        doc.moveDown(0.5);
        doc.fillColor("#0f172a").fontSize(10);
        Object.entries(reportData.meta).forEach(([k, v]) => {
          doc.text(`• ${k}: ${v}`);
        });
        doc.moveDown(1);
      }

      // Compiled Figures & Metrics
      if (reportData.metrics && reportData.metrics.length > 0) {
        doc.fillColor("#1e3a8a").fontSize(12).text("Compiled Audit Figures & Statutory Metrics", { underline: true });
        doc.moveDown(0.5);
        doc.fillColor("#0f172a").fontSize(10);
        reportData.metrics.forEach((m) => {
          doc.text(`• ${m.label}: ${m.value}`);
        });
        doc.moveDown(1);
      }

      // Optional Body Text (for inquiry letters or custom text)
      if (reportData.bodyText) {
        doc.fillColor("#1e3a8a").fontSize(12).text("Official Statement & Contents", { underline: true });
        doc.moveDown(0.5);
        doc.fillColor("#0f172a").fontSize(9).text(reportData.bodyText, { lineGap: 3 });
        doc.moveDown(1);
      }

      // Footer notice
      doc.moveDown(2);
      doc.fontSize(8).fillColor("#475569").text(
        "Statutory Notice: Document compiled under Section 15 of RFCTLARR Act 2013. Digitally authorized by LandGuard AI Special Revenue Officer.",
        { align: "center" }
      );

      doc.end();
    });
  }
}
